# scrape_configs:
#   - job_name: "prometheus"
#     static_configs:
#       - targets: ["localhost:9090"]

#   - job_name: "delivery_service"
#     static_configs:
#       - targets: ["172.17.0.1:8000"]

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name: "delivery_service"
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["host.docker.internal:9100"]

rule_files:
  - /etc/prometheus/alert_rules.yml 
